{
  "language": "node_js",
  "env": [
    "DATABASE_URL=postgresql://postgres@localhost:5432/regdb_test"
  ],
  "node_js": [
    "12"
  ],
  "before_script": [
    "psql -c 'create database  regdb_test;' -U postgres",
    "psql -U postgres -d regdb_test -a -f regdb_test.sql"
  ],
  "services": [
    "postgresql"
  ]
}